### ISSUE TITLE
Function name change

### ISSUE THREAD

**Issue by HyzamAli** [HyzamAli/FirebaseChat#9]
In FirebaseChat/app/src/main/java/com/tut/firebasechat/views/fragments/VerifyOtpFragment.kt

change function name intentHome() to intentRegistration

**Comment by rasfarrf5** [comment]
Hi HyzamAli,
I would like to work on this project. So this is just function name change?

**Comment by HyzamAli** [comment]
@rasfarrf5 Sure, make sure you checkout the latest branch. To merge, please put a pull request with issue linked to it.

**Comment by rasfarrf5** [comment]
Changes are done. Please help to verify and approve it. Thanks

**Comment by HyzamAli** [comment]
Thank you for your contribution☺️
